#' Matrix representation of the order generated by a set of intervals
#'
#' Represent the order generated by a set of intervals as a Boolean matrix.
#' This is a common input format for programs that operate on partial orders and
#' can be used to compute the distance between those orders.
#'
#' See sections 3 and 6 of \insertCite{rising2023orderRanks;textual}{orderRanks}.
#'
#' @param intervals data frame (see [orderRanks::orderRanks] for
#' the required format)
#' @param strict is this <= or <?
#' @param binary output is coded as 0/1 if TRUE and FALSE/TRUE otherwise
#'
#' @return A boolean matrix.  If strict is set to TRUE, the (i, j)th entry is
#' intervals\[i, 'right'\] < intervals\[j, 'left'\].  If strict is set to false, <=
#' is used in place of <.
#' @export
#'
#' @references
#' \insertAllCited{}
#'
#' @examples
#' intervals <- antiRetroviralIntervals()[2:8, ]
#' intervalsToMatrix(intervals)
#' intervalsToMatrix(intervals, strict = TRUE)
#' intervalsToMatrix(intervals, binary = TRUE)
intervalsToMatrix <- function(intervals, strict = FALSE, binary = FALSE)
{
  errorCheckIntervals(intervals)

  f <- function(x)
  {
    i <- x[1]
    j <- x[2]
    intervals[i, 'right'] <= intervals[j, 'left']
  }

  n <- nrow(intervals)
  M <- expand.grid(1:n, 1:n) |> apply(1, f)
  toMatrix(M, n, strict, binary)
}
