#' Compare intervals
#'
#' Given a data frame representing a set of intervals, return true if row i is
#' less than row j under the order generated by the intervals and false
#' otherwise.
#'
#' See section 3 of \insertCite{rising2023orderRanks;textual}{orderRanks}.
#'
#' @param intervals data frame (see [orderRanks::orderRanks] for
#' the required format)
#' @param i row index of left-hand side of inequality
#' @param j row index of right-hand side of inequaltiy
#'
#' @return Boolean value
#' @export
#'
#' @references
#' \insertAllCited{}
#'
#' @examples
#' intervals <- antiRetroviralIntervals()
#' lessThan(intervals, 2, 3)
#' lessThan(intervals, 1, 10)
lessThan <- function(intervals, i, j)
{
  errorCheckIntervals(intervals)

  intervals[i, 'right'] <= intervals[j, 'left']
}
