#' Matrix representation of the order generated by a ranking
#'
#' Represent the order generated by a ranking as a Boolean matrix.  This is a
#' common input format for programs that operate on partial orders and can be
#' used to compute the distance between those orders.
#'
#' See sections 3 and 6 of \insertCite{rising2023orderRanks;textual}{orderRanks}.
#'
#' @param ranking rank vector (see [orderRanks::orderRanks] for format)
#' @param strict is this <= or <?
#' @param binary output is coded as 0/1 if TRUE and FALSE/TRUE otherwise
#'
#' @return A boolean matrix.  If strict is set to TRUE, the (i, j)th entry is
#' ranking\[i\] < ranking\[j\].  If strict is set to false, <= is used in place
#' of <.
#' @export
#'
#' @references
#' \insertAllCited{}
#'
#' @examples
#' r1 <- rank(antiRetroviralIntervals()[2:8, 'left'], ties.method = 'min')
#' rankingToMatrix(r1)
#' rankingToMatrix(r1, strict = TRUE)
#' rankingToMatrix(r1, binary = TRUE)
#'
#' r2 <- rank(antiRetroviralIntervals()[2:8, 'right'], ties.method = 'min')
#' rankingToMatrix(r2)
#' rankingToMatrix(r2, strict = TRUE)
#' rankingToMatrix(r2, binary = TRUE)
rankingToMatrix <- function(ranking, strict = FALSE, binary = FALSE)
{
  errorCheckRanking(ranking)

  f <- function(x)
  {
    i <- x[1]
    j <- x[2]
    ranking[i] < ranking[j]
  }

  n <- length(ranking)
  M <- expand.grid(1:n, 1:n) |> apply(1, f)
  toMatrix(M, n, strict, binary)
}
