#' Calculate the distance between the orders generated by two rankings
#'
#' Given two rankings, this method determines the distance between the orders
#' they represent.
#'
#' See section 6 of \insertCite{rising2023orderRanks;textual}{orderRanks}.
#'
#' @param r1 ranking vector (see [orderRanks::orderRanks] for format)
#' @param r2 ranking vector
#' @param normalize boolean if TRUE, normalize the distance to \[0, 1\]
#'
#' @return numeric measure of distance
#' @export
#'
#' @references
#' \insertAllCited{}
#'
#' @examples
#' rankingDistance(1:7, 1:7)
#' rankingDistance(1:7, 7:1, TRUE)
#' rankingDistance(1:7, 7:1)
#' rankingDistance(1:7, c(7, 1:6))
#' rankingDistance(1:7, c(2, 1, 3:7))
rankingDistance <- function(r1, r2, normalize = FALSE)
{
  errorCheckRankings(r1, r2)

  d <- getRankDistance(r1, r2)
  if (normalize)
  {
    p <- length(r1)
    d <- d / (p * (p - 1))
  }
  d
}
