# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCompatibility <- function(ranking, left, right) {
    .Call(`_orderRanks_getCompatibility`, ranking, left, right)
}

getRankDistance <- function(r1, r2) {
    .Call(`_orderRanks_getRankDistance`, r1, r2)
}

getRankIntervals <- function(left, right) {
    .Call(`_orderRanks_getRankIntervals`, left, right)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_orderRanks_RcppExport_registerCCallable', PACKAGE = 'orderRanks')
})
